/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Maksym Nekleva (https://sketchfab.com/maksym.nekleva)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plastic-credit-card-4056fbcafe5e44e5810c84a2a836f9c1
Title: Plastic Credit Card
*/

import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import { useRef } from "react";

import isCardScene from "../assets/3d/plastic_credit_card.glb";

export function Card3(props) {
  const { nodes, materials } = useGLTF(isCardScene);
  const cardRef = useRef();

  return (
    <a.group {...props} ref={cardRef} dispose={null}>
      <mesh
        // castShadow
        // receiveShadow
        geometry={nodes.Card__0.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </a.group>
  );
}

useGLTF.preload("/plastic_credit_card.glb");
