/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gustavo Rocha (https://sketchfab.com/GuuhCreations)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nubank-credit-card-2bab2563b5a94d9c82bf4591e0288d03
Title: Nubank Credit Card
*/

// import React, { useRef } from "react";

import { a } from "@react-spring/three";
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
// import { useFrame, useThree } from "@react-three/fiber";

import isCardScene from "../assets/3d/nubank_credit_card.glb";

const Card1 = (props) => {
  const { nodes, materials } = useGLTF(isCardScene);
  const cardRef = useRef();
  return (
    <a.group ref={cardRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh
          //   castShadow
          //   receiveShadow
          geometry={nodes.Cartao_Mat_0.geometry}
          material={materials.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </a.group>
  );
};

// useGLTF.preload("/nubank_credit_card.glb");

export default Card1;
