/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aya Dja (https://sketchfab.com/ayadja1977)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/credit-card-4c4117d766f342cc9e0fa3d79e9de654
Title: Credit card
*/

import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import { useRef } from "react";

import isCardScene from "../assets/3d/credit_card.glb";

export function Card2(props) {
  const { nodes, materials } = useGLTF(isCardScene);
  const cardRef = useRef();
  return (
    <a.group {...props} ref={cardRef} dispose={null}>
      <group rotation={[0, 0, -Math.PI / 2]} scale={[0.004]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.border} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.inside} />
      </group>
      <group rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.05, 1.6]}>
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.card_face_1}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.border_card}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.black_back}
        />
        <mesh geometry={nodes.Object_12.geometry} material={materials.back} />
      </group>
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.numbers}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.004}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.material}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.004}
      />
    </a.group>
  );
}

// useGLTF.preload("/credit_card.glb");
